/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videoconference;

import BLL.BUS;
import DTO.PhongBan;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class LoginClient extends javax.swing.JFrame {
////////////
    ArrayList<PhongBan> arrPhong;
    BUS bus;
////////////
    /**
     * Creates new form LoginClient
     */
    public LoginClient() {
        initComponents();
        bus=new BUS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDangKi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã phòng ban");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 50));

        jLabel2.setText("Mật khẩu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 174, 80, 30));
        getContentPane().add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, -1));
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, -1));

        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoconference/sign_in.png"))); // NOI18N
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignInMouseExited(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 50));

        jLabel4.setText("Chưa đăng kí ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        btnDangKi.setText("Đăng kí");
        btnDangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangKiMouseClicked(evt);
            }
        });
        getContentPane().add(btnDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel5.setText("HỘI NGHỊ TRỰC TUYẾN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoconference/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked
        arrPhong=new ArrayList<>();
        String[] tenphong=new String[2];
        if(txtMaPhong.getText().length()>0&&txtMaPhong.getText().length()>0)
        {
            boolean xacnhan=false;
            try{
            bus.load(arrPhong);
            if(arrPhong.size()>0)
            {
                for(int i=0;i<arrPhong.size();i++)
                {
                if(txtMaPhong.getText().equals(arrPhong.get(i).getId())
                        &&txtMatKhau.getText().equals(arrPhong.get(i).getMatkhau()))
                {
                    xacnhan=true;
                    tenphong[0]=arrPhong.get(i).getTen();
                    tenphong[1]=arrPhong.get(i).getId();
                    break;
                }
                    
                }         
                    
                if(xacnhan)
                {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                       
                         this.setVisible(false);
                         Client.main(tenphong);
                         //new Client().setVisible(true);
                         
                }
                 else
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng thông tin đã đăng kí!");
 
            }
            else
                JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu");
        }catch(Exception ex)
                {
                JOptionPane.showMessageDialog(this,ex.getMessage());
                }
            
        
        }else
             JOptionPane.showMessageDialog(this, "Bạn vui lòng nhập đầy đủ!");
                  
       //bus.load(arrPhong);
    }//GEN-LAST:event_btnSignInMouseClicked

    private void btnSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseEntered
         btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoconference/sign_in2.jpg")));
    }//GEN-LAST:event_btnSignInMouseEntered

    private void btnSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseExited
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoconference/sign_in.png")));
    }//GEN-LAST:event_btnSignInMouseExited

    private void btnDangKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKiMouseClicked
           new SignUpClient().setVisible(true);
    }//GEN-LAST:event_btnDangKiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JLabel btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
